// This file is auto-generated by @hey-api/openapi-ts

import { type Client, formDataBodySerializer, type Options as Options2, type TDataShape } from './client';
import { client } from './client.gen';
import type { CreateBlogData, CreateBlogResponses, CreateCategoryData, CreateCategoryResponses, CreateCourseData, CreateCourseResponses, CreateTagData, CreateTagResponses, DeleteBlogData, DeleteBlogResponses, DeleteCategoryData, DeleteCategoryResponses, DeleteCourseData, DeleteCourseResponses, DeleteMediaData, DeleteMediaResponses, DeleteMessageData, DeleteMessageResponses, DeleteTagData, DeleteTagResponses, GetAllCategoriesData, GetAllCategoriesResponses, GetAllCoursesData, GetAllCoursesResponses, GetAllMediaData, GetAllMediaResponses, GetAllMessagesData, GetAllMessagesResponses, GetAllTagsData, GetAllTagsResponses, GetBlogBySlugData, GetBlogBySlugResponses, GetCourseBySlugData, GetCourseBySlugResponses, GetMeData, GetMeResponses, GetMessageByIdData, GetMessageByIdResponses, GetPublishedBlogsData, GetPublishedBlogsResponses, HealthData, HealthResponses, LoginData, LoginResponses, LogoutData, LogoutResponses, RefreshTokenData, RefreshTokenResponses, RootData, RootResponses, SubmitContactFormData, SubmitContactFormResponses, UpdateBlogData, UpdateBlogResponses, UpdateCourseData, UpdateCourseResponses, UpdateStatusData, UpdateStatusResponses, UploadMediaData, UploadMediaResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Get all tags
 */
export const getAllTags = <ThrowOnError extends boolean = false>(options?: Options<GetAllTagsData, ThrowOnError>) => (options?.client ?? client).get<GetAllTagsResponses, unknown, ThrowOnError>({ url: '/api/v1/tags', ...options });

/**
 * Create a new tag
 */
export const createTag = <ThrowOnError extends boolean = false>(options: Options<CreateTagData, ThrowOnError>) => (options.client ?? client).post<CreateTagResponses, unknown, ThrowOnError>({
    url: '/api/v1/tags',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete a tag
 */
export const deleteTag = <ThrowOnError extends boolean = false>(options: Options<DeleteTagData, ThrowOnError>) => (options.client ?? client).delete<DeleteTagResponses, unknown, ThrowOnError>({ url: '/api/v1/tags/{id}', ...options });

/**
 * Upload media file
 */
export const uploadMedia = <ThrowOnError extends boolean = false>(options: Options<UploadMediaData, ThrowOnError>) => (options.client ?? client).post<UploadMediaResponses, unknown, ThrowOnError>({
    ...formDataBodySerializer,
    url: '/api/v1/media/upload',
    ...options,
    headers: {
        'Content-Type': null,
        ...options.headers
    }
});

/**
 * Get all media for the current user
 */
export const getAllMedia = <ThrowOnError extends boolean = false>(options?: Options<GetAllMediaData, ThrowOnError>) => (options?.client ?? client).get<GetAllMediaResponses, unknown, ThrowOnError>({ url: '/api/v1/media', ...options });

/**
 * Delete media by ID
 */
export const deleteMedia = <ThrowOnError extends boolean = false>(options: Options<DeleteMediaData, ThrowOnError>) => (options.client ?? client).delete<DeleteMediaResponses, unknown, ThrowOnError>({ url: '/api/v1/media/{id}', ...options });

export const root = <ThrowOnError extends boolean = false>(options?: Options<RootData, ThrowOnError>) => (options?.client ?? client).get<RootResponses, unknown, ThrowOnError>({ url: '/', ...options });

export const health = <ThrowOnError extends boolean = false>(options?: Options<HealthData, ThrowOnError>) => (options?.client ?? client).get<HealthResponses, unknown, ThrowOnError>({ url: '/health', ...options });

/**
 * Get all courses with pagination
 */
export const getAllCourses = <ThrowOnError extends boolean = false>(options?: Options<GetAllCoursesData, ThrowOnError>) => (options?.client ?? client).get<GetAllCoursesResponses, unknown, ThrowOnError>({ url: '/api/v1/courses', ...options });

/**
 * Create a new course
 */
export const createCourse = <ThrowOnError extends boolean = false>(options: Options<CreateCourseData, ThrowOnError>) => (options.client ?? client).post<CreateCourseResponses, unknown, ThrowOnError>({
    url: '/api/v1/courses',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get course by slug
 */
export const getCourseBySlug = <ThrowOnError extends boolean = false>(options: Options<GetCourseBySlugData, ThrowOnError>) => (options.client ?? client).get<GetCourseBySlugResponses, unknown, ThrowOnError>({ url: '/api/v1/courses/{slug}', ...options });

/**
 * Delete a course
 */
export const deleteCourse = <ThrowOnError extends boolean = false>(options: Options<DeleteCourseData, ThrowOnError>) => (options.client ?? client).delete<DeleteCourseResponses, unknown, ThrowOnError>({ url: '/api/v1/courses/{id}', ...options });

/**
 * Update a course
 */
export const updateCourse = <ThrowOnError extends boolean = false>(options: Options<UpdateCourseData, ThrowOnError>) => (options.client ?? client).put<UpdateCourseResponses, unknown, ThrowOnError>({
    url: '/api/v1/courses/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get all contact messages (Admin only)
 */
export const getAllMessages = <ThrowOnError extends boolean = false>(options?: Options<GetAllMessagesData, ThrowOnError>) => (options?.client ?? client).get<GetAllMessagesResponses, unknown, ThrowOnError>({ url: '/api/v1/contact-us', ...options });

/**
 * Submit a contact us form
 */
export const submitContactForm = <ThrowOnError extends boolean = false>(options: Options<SubmitContactFormData, ThrowOnError>) => (options.client ?? client).post<SubmitContactFormResponses, unknown, ThrowOnError>({
    url: '/api/v1/contact-us',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete a contact message (Admin only)
 */
export const deleteMessage = <ThrowOnError extends boolean = false>(options: Options<DeleteMessageData, ThrowOnError>) => (options.client ?? client).delete<DeleteMessageResponses, unknown, ThrowOnError>({ url: '/api/v1/contact-us/{id}', ...options });

/**
 * Get a contact message by ID (Admin only)
 */
export const getMessageById = <ThrowOnError extends boolean = false>(options: Options<GetMessageByIdData, ThrowOnError>) => (options.client ?? client).get<GetMessageByIdResponses, unknown, ThrowOnError>({ url: '/api/v1/contact-us/{id}', ...options });

/**
 * Update a contact message status (Admin only)
 */
export const updateStatus = <ThrowOnError extends boolean = false>(options: Options<UpdateStatusData, ThrowOnError>) => (options.client ?? client).patch<UpdateStatusResponses, unknown, ThrowOnError>({
    url: '/api/v1/contact-us/{id}/status',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get all categories
 */
export const getAllCategories = <ThrowOnError extends boolean = false>(options?: Options<GetAllCategoriesData, ThrowOnError>) => (options?.client ?? client).get<GetAllCategoriesResponses, unknown, ThrowOnError>({ url: '/api/v1/categories', ...options });

/**
 * Create a new category
 */
export const createCategory = <ThrowOnError extends boolean = false>(options: Options<CreateCategoryData, ThrowOnError>) => (options.client ?? client).post<CreateCategoryResponses, unknown, ThrowOnError>({
    url: '/api/v1/categories',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete a category
 */
export const deleteCategory = <ThrowOnError extends boolean = false>(options: Options<DeleteCategoryData, ThrowOnError>) => (options.client ?? client).delete<DeleteCategoryResponses, unknown, ThrowOnError>({ url: '/api/v1/categories/{id}', ...options });

/**
 * Get all published blogs (public endpoint)
 */
export const getPublishedBlogs = <ThrowOnError extends boolean = false>(options?: Options<GetPublishedBlogsData, ThrowOnError>) => (options?.client ?? client).get<GetPublishedBlogsResponses, unknown, ThrowOnError>({ url: '/api/v1/blogs', ...options });

/**
 * Create a new blog
 */
export const createBlog = <ThrowOnError extends boolean = false>(options: Options<CreateBlogData, ThrowOnError>) => (options.client ?? client).post<CreateBlogResponses, unknown, ThrowOnError>({
    url: '/api/v1/blogs',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get blog by slug (public endpoint)
 */
export const getBlogBySlug = <ThrowOnError extends boolean = false>(options: Options<GetBlogBySlugData, ThrowOnError>) => (options.client ?? client).get<GetBlogBySlugResponses, unknown, ThrowOnError>({ url: '/api/v1/blogs/{slug}', ...options });

/**
 * Delete a blog
 */
export const deleteBlog = <ThrowOnError extends boolean = false>(options: Options<DeleteBlogData, ThrowOnError>) => (options.client ?? client).delete<DeleteBlogResponses, unknown, ThrowOnError>({ url: '/api/v1/blogs/{id}', ...options });

/**
 * Update a blog
 */
export const updateBlog = <ThrowOnError extends boolean = false>(options: Options<UpdateBlogData, ThrowOnError>) => (options.client ?? client).put<UpdateBlogResponses, unknown, ThrowOnError>({
    url: '/api/v1/blogs/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Login user
 */
export const login = <ThrowOnError extends boolean = false>(options: Options<LoginData, ThrowOnError>) => (options.client ?? client).post<LoginResponses, unknown, ThrowOnError>({
    url: '/api/v1/auth/login',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const logout = <ThrowOnError extends boolean = false>(options?: Options<LogoutData, ThrowOnError>) => (options?.client ?? client).post<LogoutResponses, unknown, ThrowOnError>({ url: '/api/v1/auth/logout', ...options });

/**
 * Refresh access token
 */
export const refreshToken = <ThrowOnError extends boolean = false>(options?: Options<RefreshTokenData, ThrowOnError>) => (options?.client ?? client).post<RefreshTokenResponses, unknown, ThrowOnError>({ url: '/api/v1/auth/refresh-token', ...options });

/**
 * Get current user profile
 */
export const getMe = <ThrowOnError extends boolean = false>(options?: Options<GetMeData, ThrowOnError>) => (options?.client ?? client).get<GetMeResponses, unknown, ThrowOnError>({ url: '/api/v1/auth/me', ...options });
