// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://api.e-thekka.com/api/v1' | 'http://localhost:4500/api/v1' | (string & {});
};

export type Tag = {
    id: string;
    createdAt: string;
    updatedAt: string;
    deletedAt: string;
    name: string;
    isPublic: boolean;
};

export type PaginationInterface = {
    total: number;
    page: number;
    limit: number;
    totalPages: number;
};

export type ResponseInterfaceTagArray = {
    data: Array<Tag> | null;
    success: boolean;
    message: string;
    status?: string;
    pagination?: PaginationInterface;
};

export type ResponseInterfaceTag = {
    data: Tag | null;
    success: boolean;
    message: string;
    status?: string;
    pagination?: PaginationInterface;
};

export type CreateTagDto = {
    name: string;
};

export type ResponseInterfaceNull = {
    data: null;
    success: boolean;
    message: string;
    status?: string;
    pagination?: PaginationInterface;
};

export type MediaDocumentType = 'IMAGE' | 'VIDEO';

export type MediaEntityType = 'BLOG' | 'LESSON' | 'COURSE';

export type LogModule = 'AUTH' | 'USER' | 'ADMIN' | 'CONTRACTOR' | 'CLIENT' | 'AGENT' | 'PROJECT' | 'TASK' | 'PAYMENT' | 'NOTIFICATION' | 'REPORT' | 'SETTINGS' | 'SYSTEM' | 'OTHER';

export type LogAction = 'CREATE' | 'READ' | 'UPDATE' | 'DELETE' | 'LOGIN' | 'LOGOUT' | 'ACCESS' | 'EXPORT' | 'IMPORT' | 'OTHER' | 'EMAIL_VERIFIED_REQUEST' | 'EMAIL_VERIFIED' | 'EMAIL_VERIFICATION_OTP' | 'FORGOT_PASSWORD' | 'PASSWORD_RESET' | 'PASSWORD_CHANGE' | 'STATUS_CHANGE';

export type LogSeverity = 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL';

/**
 * Construct a type with a set of properties K of type T
 */
export type RecordStringAny = {
    [key: string]: unknown;
};

export type User = {
    id: string;
    createdAt: string;
    updatedAt: string;
    deletedAt: string;
    fullName: string;
    email: string;
    password: string;
    logs: Array<Log>;
    blogs: Array<Blog>;
    tokens: Array<Token>;
};

export type Log = {
    id: string;
    createdAt: string;
    updatedAt: string;
    deletedAt: string;
    module: LogModule;
    action: LogAction;
    severity: LogSeverity;
    details: RecordStringAny;
    ipAddress: string;
    userAgent: string;
    resource: string;
    description: string;
    errorMessage: string;
    errorStack: string;
    user: User;
};

export type Media = {
    id: string;
    createdAt: string;
    updatedAt: string;
    deletedAt: string;
    mimeType: string;
    name: string;
    documentType: MediaDocumentType;
    entityType: MediaEntityType;
    entityId?: string;
    originalFileName: string;
    url: string;
    user: User;
};

export type Blog = {
    id: string;
    createdAt: string;
    updatedAt: string;
    deletedAt: string;
    title: string;
    slug: string;
    excerpt: string;
    thumbnail: Array<Media>;
    content: string;
    author: User;
};

export type TokenEnum = 'ACCESS' | 'REFRESH' | 'FORGET_PASSWORD' | 'VERIFY_EMAIL' | 'CHANGE_PASSWORD_OTP';

export type Token = {
    id: string;
    createdAt: string;
    updatedAt: string;
    deletedAt: string;
    tokenHash: string;
    type: TokenEnum;
    deviceId?: string;
    ipHash?: string;
    expiresAt: string;
    usedAt?: string;
    revokedAt?: string;
    user?: User;
};

export type ResponseInterfaceMedia = {
    data: Media | null;
    success: boolean;
    message: string;
    status?: string;
    pagination?: PaginationInterface;
};

export type ResponseInterfaceMediaArray = {
    data: Array<Media> | null;
    success: boolean;
    message: string;
    status?: string;
    pagination?: PaginationInterface;
};

export type ResponseInterfaceBoolean = {
    data: boolean | null;
    success: boolean;
    message: string;
    status?: string;
    pagination?: PaginationInterface;
};

export type LessonStatus = 'NOT_STARTED' | 'IN_PROGRESS' | 'COMPLETED';

export type CourseEntity = {
    id: string;
    createdAt: string;
    updatedAt: string;
    deletedAt: string;
    title: string;
    slug: string;
    excerpt: string;
    thumbnail: Array<Media>;
    featuredImage?: Array<Media>;
    lessons: Array<LessonEntity>;
};

export type LessonEntity = {
    id: string;
    createdAt: string;
    updatedAt: string;
    deletedAt: string;
    title: string;
    slug: string;
    excerpt: string;
    duration: string;
    status: LessonStatus;
    course: CourseEntity;
};

export type ResponseInterfaceCourseEntityArray = {
    data: Array<CourseEntity> | null;
    success: boolean;
    message: string;
    status?: string;
    pagination?: PaginationInterface;
};

export type ResponseInterfaceCourseEntity = {
    data: CourseEntity | null;
    success: boolean;
    message: string;
    status?: string;
    pagination?: PaginationInterface;
};

export type CreateCourseDto = {
    title: string;
    excerpt: string;
    thumbnailId?: string;
    featuredImageIds?: Array<string>;
};

export type UpdateCourseDto = {
    title?: string;
    excerpt?: string;
    thumbnailId?: string;
    featuredImageIds?: Array<string>;
};

export type ContactUsStatus = 'PENDING' | 'READ' | 'RESPONDED' | 'ARCHIVED';

export type ContactUs = {
    id: string;
    createdAt: string;
    updatedAt: string;
    deletedAt: string;
    name: string;
    email: string;
    subject: string;
    message: string;
    status: ContactUsStatus;
};

export type ResponseInterfaceContactUs = {
    data: ContactUs | null;
    success: boolean;
    message: string;
    status?: string;
    pagination?: PaginationInterface;
};

export type CreateContactUsDto = {
    /**
     * Full name of the person contacting
     */
    name: string;
    /**
     * Email address of the person
     */
    email: string;
    /**
     * Subject of the message
     */
    subject: string;
    /**
     * The message content
     */
    message: string;
};

export type ResponseInterfaceContactUsArray = {
    data: Array<ContactUs> | null;
    success: boolean;
    message: string;
    status?: string;
    pagination?: PaginationInterface;
};

export type UpdateContactUsStatusDto = {
    /**
     * The new status for the contact message
     */
    status: string;
};

export type Category = {
    id: string;
    createdAt: string;
    updatedAt: string;
    deletedAt: string;
    name: string;
    isPublic: boolean;
};

export type ResponseInterfaceCategoryArray = {
    data: Array<Category> | null;
    success: boolean;
    message: string;
    status?: string;
    pagination?: PaginationInterface;
};

export type ResponseInterfaceCategory = {
    data: Category | null;
    success: boolean;
    message: string;
    status?: string;
    pagination?: PaginationInterface;
};

export type CreateCategoryDto = {
    name: string;
};

export type ResponseInterfaceBlogArray = {
    data: Array<Blog> | null;
    success: boolean;
    message: string;
    status?: string;
    pagination?: PaginationInterface;
};

export type ResponseInterfaceBlog = {
    data: Blog | null;
    success: boolean;
    message: string;
    status?: string;
    pagination?: PaginationInterface;
};

export type CreateBlogDto = {
    title: string;
    excerpt: string;
    content: string;
    thumbnailId?: string;
    isPublished?: boolean;
};

export type UpdateBlogDto = {
    title?: string;
    excerpt?: string;
    content?: string;
    thumbnailId?: string;
    isPublished?: boolean;
};

export type UserLoginDto = {
    email: string;
    password: string;
};

export type ResponseInterfaceAny = {
    data: unknown;
    success: boolean;
    message: string;
    status?: string;
    pagination?: PaginationInterface;
};

export type GetAllTagsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/tags';
};

export type GetAllTagsResponses = {
    /**
     * Ok
     */
    200: ResponseInterfaceTagArray;
};

export type GetAllTagsResponse = GetAllTagsResponses[keyof GetAllTagsResponses];

export type CreateTagData = {
    body: CreateTagDto;
    path?: never;
    query?: never;
    url: '/api/v1/tags';
};

export type CreateTagResponses = {
    /**
     * Ok
     */
    200: ResponseInterfaceTag;
};

export type CreateTagResponse = CreateTagResponses[keyof CreateTagResponses];

export type DeleteTagData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/tags/{id}';
};

export type DeleteTagResponses = {
    /**
     * Ok
     */
    200: ResponseInterfaceNull;
};

export type DeleteTagResponse = DeleteTagResponses[keyof DeleteTagResponses];

export type UploadMediaData = {
    body: {
        file: Blob | File;
        documentType: string;
        entityType: string;
        entityId?: string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/media/upload';
};

export type UploadMediaResponses = {
    /**
     * Ok
     */
    200: ResponseInterfaceMedia;
};

export type UploadMediaResponse = UploadMediaResponses[keyof UploadMediaResponses];

export type GetAllMediaData = {
    body?: never;
    path?: never;
    query?: {
        page?: number;
        limit?: number;
        entityType?: MediaEntityType;
        entityId?: string;
    };
    url: '/api/v1/media';
};

export type GetAllMediaResponses = {
    /**
     * Ok
     */
    200: ResponseInterfaceMediaArray;
};

export type GetAllMediaResponse = GetAllMediaResponses[keyof GetAllMediaResponses];

export type DeleteMediaData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/media/{id}';
};

export type DeleteMediaResponses = {
    /**
     * Ok
     */
    200: ResponseInterfaceBoolean;
};

export type DeleteMediaResponse = DeleteMediaResponses[keyof DeleteMediaResponses];

export type RootData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type RootResponses = {
    /**
     * Ok
     */
    200: {
        env: string;
        version: unknown;
        uptime: string;
        status: string;
    };
};

export type RootResponse = RootResponses[keyof RootResponses];

export type HealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthResponses = {
    /**
     * Ok
     */
    200: {
        time: string;
        redis: string;
        db: string;
        env: string;
        version: unknown;
        uptime: number;
        status: string;
    };
};

export type HealthResponse = HealthResponses[keyof HealthResponses];

export type GetAllCoursesData = {
    body?: never;
    path?: never;
    query?: {
        limit?: number;
        page?: number;
        search?: string;
    };
    url: '/api/v1/courses';
};

export type GetAllCoursesResponses = {
    /**
     * Ok
     */
    200: ResponseInterfaceCourseEntityArray;
};

export type GetAllCoursesResponse = GetAllCoursesResponses[keyof GetAllCoursesResponses];

export type CreateCourseData = {
    body: CreateCourseDto;
    path?: never;
    query?: never;
    url: '/api/v1/courses';
};

export type CreateCourseResponses = {
    /**
     * Ok
     */
    200: ResponseInterfaceCourseEntity;
};

export type CreateCourseResponse = CreateCourseResponses[keyof CreateCourseResponses];

export type GetCourseBySlugData = {
    body?: never;
    path: {
        slug: string;
    };
    query?: never;
    url: '/api/v1/courses/{slug}';
};

export type GetCourseBySlugResponses = {
    /**
     * Ok
     */
    200: ResponseInterfaceCourseEntity;
};

export type GetCourseBySlugResponse = GetCourseBySlugResponses[keyof GetCourseBySlugResponses];

export type DeleteCourseData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/courses/{id}';
};

export type DeleteCourseResponses = {
    /**
     * Ok
     */
    200: ResponseInterfaceNull;
};

export type DeleteCourseResponse = DeleteCourseResponses[keyof DeleteCourseResponses];

export type UpdateCourseData = {
    body: UpdateCourseDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/courses/{id}';
};

export type UpdateCourseResponses = {
    /**
     * Ok
     */
    200: ResponseInterfaceCourseEntity;
};

export type UpdateCourseResponse = UpdateCourseResponses[keyof UpdateCourseResponses];

export type GetAllMessagesData = {
    body?: never;
    path?: never;
    query?: {
        limit?: number;
        page?: number;
        status?: string;
    };
    url: '/api/v1/contact-us';
};

export type GetAllMessagesResponses = {
    /**
     * Ok
     */
    200: ResponseInterfaceContactUsArray;
};

export type GetAllMessagesResponse = GetAllMessagesResponses[keyof GetAllMessagesResponses];

export type SubmitContactFormData = {
    body: CreateContactUsDto;
    path?: never;
    query?: never;
    url: '/api/v1/contact-us';
};

export type SubmitContactFormResponses = {
    /**
     * Ok
     */
    200: ResponseInterfaceContactUs;
};

export type SubmitContactFormResponse = SubmitContactFormResponses[keyof SubmitContactFormResponses];

export type DeleteMessageData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/contact-us/{id}';
};

export type DeleteMessageResponses = {
    /**
     * Ok
     */
    200: ResponseInterfaceNull;
};

export type DeleteMessageResponse = DeleteMessageResponses[keyof DeleteMessageResponses];

export type GetMessageByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/contact-us/{id}';
};

export type GetMessageByIdResponses = {
    /**
     * Ok
     */
    200: ResponseInterfaceContactUs;
};

export type GetMessageByIdResponse = GetMessageByIdResponses[keyof GetMessageByIdResponses];

export type UpdateStatusData = {
    body: UpdateContactUsStatusDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/contact-us/{id}/status';
};

export type UpdateStatusResponses = {
    /**
     * Ok
     */
    200: ResponseInterfaceContactUs;
};

export type UpdateStatusResponse = UpdateStatusResponses[keyof UpdateStatusResponses];

export type GetAllCategoriesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/categories';
};

export type GetAllCategoriesResponses = {
    /**
     * Ok
     */
    200: ResponseInterfaceCategoryArray;
};

export type GetAllCategoriesResponse = GetAllCategoriesResponses[keyof GetAllCategoriesResponses];

export type CreateCategoryData = {
    body: CreateCategoryDto;
    path?: never;
    query?: never;
    url: '/api/v1/categories';
};

export type CreateCategoryResponses = {
    /**
     * Ok
     */
    200: ResponseInterfaceCategory;
};

export type CreateCategoryResponse = CreateCategoryResponses[keyof CreateCategoryResponses];

export type DeleteCategoryData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/categories/{id}';
};

export type DeleteCategoryResponses = {
    /**
     * Ok
     */
    200: ResponseInterfaceNull;
};

export type DeleteCategoryResponse = DeleteCategoryResponses[keyof DeleteCategoryResponses];

export type GetPublishedBlogsData = {
    body?: never;
    path?: never;
    query?: {
        limit?: number;
        page?: number;
        search?: string;
    };
    url: '/api/v1/blogs';
};

export type GetPublishedBlogsResponses = {
    /**
     * Ok
     */
    200: ResponseInterfaceBlogArray;
};

export type GetPublishedBlogsResponse = GetPublishedBlogsResponses[keyof GetPublishedBlogsResponses];

export type CreateBlogData = {
    body: CreateBlogDto;
    path?: never;
    query?: never;
    url: '/api/v1/blogs';
};

export type CreateBlogResponses = {
    /**
     * Ok
     */
    200: ResponseInterfaceBlog;
};

export type CreateBlogResponse = CreateBlogResponses[keyof CreateBlogResponses];

export type GetBlogBySlugData = {
    body?: never;
    path: {
        slug: string;
    };
    query?: never;
    url: '/api/v1/blogs/{slug}';
};

export type GetBlogBySlugResponses = {
    /**
     * Ok
     */
    200: ResponseInterfaceBlog;
};

export type GetBlogBySlugResponse = GetBlogBySlugResponses[keyof GetBlogBySlugResponses];

export type DeleteBlogData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/blogs/{id}';
};

export type DeleteBlogResponses = {
    /**
     * Ok
     */
    200: ResponseInterfaceNull;
};

export type DeleteBlogResponse = DeleteBlogResponses[keyof DeleteBlogResponses];

export type UpdateBlogData = {
    body: UpdateBlogDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/blogs/{id}';
};

export type UpdateBlogResponses = {
    /**
     * Ok
     */
    200: ResponseInterfaceBlog;
};

export type UpdateBlogResponse = UpdateBlogResponses[keyof UpdateBlogResponses];

export type LoginData = {
    body: UserLoginDto;
    path?: never;
    query?: never;
    url: '/api/v1/auth/login';
};

export type LoginResponses = {
    /**
     * Ok
     */
    200: unknown;
};

export type LogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/logout';
};

export type LogoutResponses = {
    /**
     * Ok
     */
    200: ResponseInterfaceAny;
};

export type LogoutResponse = LogoutResponses[keyof LogoutResponses];

export type RefreshTokenData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/refresh-token';
};

export type RefreshTokenResponses = {
    /**
     * Ok
     */
    200: ResponseInterfaceAny;
};

export type RefreshTokenResponse = RefreshTokenResponses[keyof RefreshTokenResponses];

export type GetMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/me';
};

export type GetMeResponses = {
    /**
     * Ok
     */
    200: ResponseInterfaceAny;
};

export type GetMeResponse = GetMeResponses[keyof GetMeResponses];
