// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://api.TradeNotz.com/api/v1' | 'http://localhost:4500/api/v1' | (string & {});
};

export type NotificationType = 'INFO' | 'WARNING' | 'SUCCESS' | 'ERROR';

export type UserLoginType = 'TRADITIONAL' | 'GOOGLE';

export type UserRole = 'ADMIN' | 'CLIENT' | 'CONTRACTOR' | 'AGENT' | 'CONSULTANCY';

export type MediaDocumentType = 'CITIZENSHIP_FRONT' | 'CITIZENSHIP_BACK' | 'PASSPORT' | 'PROFILE_IMAGE' | 'COMPANY_REGISTRATION' | 'TAX_REGISTRATION' | 'COMPANY_LOGO' | 'PERSONAL_LICENSE' | 'INSURANCE_DOCUMENT' | 'PROJECT_DOCUMENT' | 'PORTFOLIO_PROJECT_PHOTO' | 'BID_DOCUMENT';

export type MediaEntityType = 'PROJECT' | 'CLIENT_PROFILE' | 'CONTRACTOR_PROFILE' | 'CONSULTANCY_PROFILE' | 'CONTRACTOR_PORTFOLIO_PROJECT' | 'CONSULTANCY_PORTFOLIO_PROJECT' | 'BID';

export type User = {
    id: string;
    createdAt: string;
    updatedAt: string;
    deletedAt: string;
    fullName: string;
    email: string;
    location?: string;
    password: string;
    phone?: string;
    isEmailVerified?: boolean;
    loginType?: UserLoginType;
    address?: string;
    avatar?: string;
    role: UserRole;
    profileImage?: Media;
    tokens?: Array<Token>;
    logs: Array<Log>;
    projects: Array<Project>;
    accountVerifications: Array<AccountVerification>;
    clientProfile: ClientProfile;
    contractorProfile: ContractorProfile;
    designConsultancyProfile: DesignConsultancyProfile;
    agentProfile?: AgentProfile;
};

export type Media = {
    id: string;
    createdAt: string;
    updatedAt: string;
    deletedAt: string;
    mimeType: string;
    name: string;
    documentType: MediaDocumentType;
    entityType: MediaEntityType;
    entityId?: string;
    originalFileName: string;
    url: string;
    user: User;
};

export type TokenEnum = 'ACCESS' | 'REFRESH' | 'FORGET_PASSWORD' | 'VERIFY_EMAIL' | 'CHANGE_PASSWORD_OTP';

export type Token = {
    id: string;
    createdAt: string;
    updatedAt: string;
    deletedAt: string;
    tokenHash: string;
    type: TokenEnum;
    deviceId?: string;
    ipHash?: string;
    expiresAt: string;
    usedAt?: string;
    revokedAt?: string;
    user?: User;
};

export type LogModule = 'AUTH' | 'USER' | 'ADMIN' | 'CONTRACTOR' | 'CLIENT' | 'AGENT' | 'PROJECT' | 'TASK' | 'PAYMENT' | 'NOTIFICATION' | 'REPORT' | 'SETTINGS' | 'SYSTEM' | 'OTHER';

export type LogAction = 'CREATE' | 'READ' | 'UPDATE' | 'DELETE' | 'LOGIN' | 'LOGOUT' | 'ACCESS' | 'EXPORT' | 'IMPORT' | 'OTHER' | 'EMAIL_VERIFIED_REQUEST' | 'EMAIL_VERIFIED' | 'EMAIL_VERIFICATION_OTP' | 'FORGOT_PASSWORD' | 'PASSWORD_RESET' | 'PASSWORD_CHANGE' | 'STATUS_CHANGE';

export type LogSeverity = 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL';

export type ActorType = 'CLIENT' | 'CONTRACTOR' | 'CONSULTANCY' | 'AGENT' | 'ADMIN' | 'SYSTEM' | 'ANONYMOUS';

/**
 * Construct a type with a set of properties K of type T
 */
export type RecordStringAny = {
    [key: string]: unknown;
};

export type Log = {
    id: string;
    createdAt: string;
    updatedAt: string;
    deletedAt: string;
    module: LogModule;
    action: LogAction;
    severity: LogSeverity;
    actorType: ActorType;
    details: RecordStringAny;
    ipAddress: string;
    userAgent: string;
    resource: string;
    description: string;
    errorMessage: string;
    errorStack: string;
    user: User;
};

export type Project = {
    id: string;
    createdAt: string;
    updatedAt: string;
    deletedAt: string;
    createdBy: User;
    awardedContractor?: User;
    bids: Array<Bids>;
    projectDocuments: Array<Media>;
    title: string;
    slug: string;
    description: string;
    category: ProjectCategory;
    location: string;
    budgetType?: ProjectBudgetType;
    minimumBudget?: number;
    maximumBudget?: number;
    target: ProjectTarget;
    preferredStartDate: string;
    preferredEndDate: string;
    bidStartedDate?: string;
    bidEndedDate?: string;
    experienceLevel?: ContractorExperienceLevel;
    similarProjectExperience?: string;
    additionalRequirements?: string;
    status: ProjectStatus;
    cancellationReason?: string;
};

export type ContractorProfile = {
    id: string;
    createdAt: string;
    updatedAt: string;
    deletedAt: string;
    user: User;
    companyName: string;
    yearsOfExperience?: number;
    specializations: string;
    teamSize: string;
    isAvailable: boolean;
    companyDescription: string;
    serviceAreas: Array<string>;
    companyRegistrationCertificate: Array<Media>;
    taxRegistrationCertificate: Array<Media>;
    personalLicense: Array<Media>;
    companyLogo: Array<Media>;
    insuranceDocument: Array<Media>;
    portfolioProjects: Array<PortfolioProject>;
};

export type PortfolioProject = {
    id: string;
    createdAt: string;
    updatedAt: string;
    deletedAt: string;
    contractor?: ContractorProfile;
    designConsultancy?: DesignConsultancyProfile;
    projectPhotos: Array<Media>;
    projectName: string;
    description: string;
    notableClients?: string;
    averageProjectValue?: number;
};

export type DesignConsultancyProfile = {
    id: string;
    createdAt: string;
    updatedAt: string;
    deletedAt: string;
    user: User;
    companyName: string;
    yearsOfExperience?: number;
    specializations: string;
    teamSize: number;
    companyDescription: string;
    serviceAreas: Array<string>;
    address?: string;
    isAvailable: boolean;
    companyRegistrationCertificate: Array<Media>;
    taxRegistrationCertificate: Array<Media>;
    companyLogo: Array<Media>;
    portfolioProjects: Array<PortfolioProject>;
};

export type BidStatus = 'PENDING' | 'ACCEPTED' | 'REJECTED';

export type Bids = {
    id: string;
    createdAt: string;
    updatedAt: string;
    deletedAt: string;
    title: string;
    project: Project;
    contractor?: ContractorProfile;
    designConsultancy?: DesignConsultancyProfile;
    cost: number;
    timelineDays: number;
    proposal?: string;
    status: BidStatus;
    rejectionReason?: string;
    documents?: Array<Media>;
};

export type ProjectCategory = 'RESIDENTIAL_CONSTRUCTION' | 'HOUSING_CONSTRUCTION' | 'COMMERCIAL_CONSTRUCTION' | 'RENOVATION';

export type ProjectBudgetType = 'FIXED_PRICE' | 'HOURS_BASED' | 'MILESTONE_BASED';

export type ProjectTarget = 'CONTRACTOR' | 'CONSULTANCY';

export type ContractorExperienceLevel = 'BEGINNER' | 'INTERMEDIATE' | 'ADVANCED';

export type ProjectStatus = 'UNDER_REVIEW' | 'OPEN_FOR_BIDDING' | 'BIDDING_CLOSED' | 'IN_PROGRESS' | 'COMPLETED' | 'CANCELLED';

export type UserVerificationStatus = 'PENDING' | 'VERIFIED' | 'REJECTED';

export type AccountVerification = {
    id: string;
    createdAt: string;
    updatedAt: string;
    deletedAt: string;
    user: User;
    actionBy?: User;
    status: UserVerificationStatus;
    comments?: string;
    verifiedAt?: string;
};

export type ClientType = 'INDIVIDUAL' | 'COMPANY';

export type ClientProfile = {
    id: string;
    createdAt: string;
    updatedAt: string;
    deletedAt: string;
    user: User;
    clientType: ClientType;
    /**
     * Only for company clients
     */
    companyName?: string;
    billingAddress?: string;
    contactPerson?: string;
    vatNumber?: string;
    companyRegistrationNo?: string;
    panNumber?: string;
    extraData?: unknown;
    citizenshipCertificate: Array<Media>;
};

export type AgentProfile = {
    id: string;
    createdAt: string;
    updatedAt: string;
    deletedAt: string;
    user: User;
    hireDate?: string;
};

export type Notification = {
    id: string;
    createdAt: string;
    updatedAt: string;
    deletedAt: string;
    title: string;
    message: string;
    type: NotificationType;
    isRead: boolean;
    recipient: User;
    recipientId: string;
};

export type PaginationInterface = {
    total: number;
    page: number;
    limit: number;
    totalPages: number;
};

export type ResponseInterfaceDataNotificationArrayCountNumber = {
    data: {
        count: number;
        data: Array<Notification>;
    } | null;
    success: boolean;
    message: string;
    status?: string;
    pagination?: PaginationInterface;
};

export type ResponseInterfaceCountNumber = {
    data: {
        count: number;
    } | null;
    success: boolean;
    message: string;
    status?: string;
    pagination?: PaginationInterface;
};

export type ResponseInterfaceNotification = {
    data: Notification | null;
    success: boolean;
    message: string;
    status?: string;
    pagination?: PaginationInterface;
};

export type ResponseInterfaceNull = {
    data: null;
    success: boolean;
    message: string;
    status?: string;
    pagination?: PaginationInterface;
};

export type MediaResponseDto = {
    id: string;
    url: string;
    documentType: MediaDocumentType;
    entityType: MediaEntityType;
    entityId: string;
    originalFileName: string;
};

export type ResponseInterfaceMediaResponseDto = {
    data: MediaResponseDto | null;
    success: boolean;
    message: string;
    status?: string;
    pagination?: PaginationInterface;
};

export type ResponseInterfaceAny = {
    data: unknown;
    success: boolean;
    message: string;
    status?: string;
    pagination?: PaginationInterface;
};

export type ResponseInterfaceMediaResponseDtoArray = {
    data: Array<MediaResponseDto> | null;
    success: boolean;
    message: string;
    status?: string;
    pagination?: PaginationInterface;
};

export type ContactUsStatus = 'PENDING' | 'READ' | 'RESPONDED' | 'ARCHIVED';

export type ContactUs = {
    id: string;
    createdAt: string;
    updatedAt: string;
    deletedAt: string;
    name: string;
    email: string;
    subject: string;
    message: string;
    status: ContactUsStatus;
};

export type ResponseInterfaceContactUs = {
    data: ContactUs | null;
    success: boolean;
    message: string;
    status?: string;
    pagination?: PaginationInterface;
};

export type CreateContactUsDto = {
    /**
     * Full name of the person contacting
     */
    name: string;
    /**
     * Email address of the person
     */
    email: string;
    /**
     * Subject of the message
     */
    subject: string;
    /**
     * The message content
     */
    message: string;
};

export type ResponseInterfaceContactUsArray = {
    data: Array<ContactUs> | null;
    success: boolean;
    message: string;
    status?: string;
    pagination?: PaginationInterface;
};

export type UpdateContactUsStatusDto = {
    /**
     * The new status for the contact message
     */
    status: string;
};

export type Blog = {
    id: string;
    createdAt: string;
    updatedAt: string;
    deletedAt: string;
    title: string;
    slug: string;
    content: string;
    isPublished: boolean;
    author: User;
    authorId: string;
    featuredImage?: Media;
    featuredImageId?: string;
    category?: string;
    tags?: Array<string>;
};

export type ResponseInterfaceBlogArray = {
    data: Array<Blog> | null;
    success: boolean;
    message: string;
    status?: string;
    pagination?: PaginationInterface;
};

export type ResponseInterfaceBlog = {
    data: Blog | null;
    success: boolean;
    message: string;
    status?: string;
    pagination?: PaginationInterface;
};

export type VerifyEmailDto = {
    email: string;
    otp: string;
};

export type ResendOtpDto = {
    email: string;
};

export type UserLoginDto = {
    email: string;
    password: string;
};

export type UserForgotPasswordDto = {
    email: string;
};

export type UserResetPasswordDto = {
    otp: string;
    email: string;
    newPassword: string;
};

export type ChangePasswordInitiateDto = {
    oldPassword: string;
};

export type ChangePasswordConfirmDto = {
    otp: string;
    newPassword: string;
};

export type ResponseInterfaceAnyArray = {
    data: Array<unknown> | null;
    success: boolean;
    message: string;
    status?: string;
    pagination?: PaginationInterface;
};

export type VerifyContractorDto = {
    reason: string;
    status: UserVerificationStatus;
    verificationId: string;
};

export type VerifyClientDto = {
    reason: string;
    verificationId: string;
    status: UserVerificationStatus;
};

export type VerifyDesignConsultancyDto = {
    reason: string;
    status: UserVerificationStatus;
    verificationId: string;
};

export type SubmitReviewDto = {
    rating: number;
    comment?: string;
};

export type CreateProjectDto = {
    title: string;
    description: string;
    category: ProjectCategory;
    location: string;
    budgetType: ProjectBudgetType;
    minimumBudget?: number;
    maximumBudget?: number;
    preferredStartDate: string;
    preferredEndDate: string;
    experienceLevel: ContractorExperienceLevel;
    similarProjectExperience?: string;
    additionalRequirements?: string;
    documents?: Array<string>;
    target: ProjectTarget;
};

export type UpdateProjectDtoByAdmin = {
    bidStartedDate: string;
    bidEndedDate: string;
    status: ProjectStatus;
    cancellationReason?: string;
    target?: ProjectTarget;
};

export type UpdateProjectDto = {
    title?: string;
    description?: string;
    category?: ProjectCategory;
    subCategory?: string;
    location?: string;
    budgetType?: ProjectBudgetType;
    minimumBudget?: number;
    maximumBudget?: number;
    preferredStartDate?: string;
    preferredEndDate?: string;
    experienceLevel?: ContractorExperienceLevel;
    similarProjectExperience?: string;
    additionalRequirements?: string;
    target?: ProjectTarget;
    documents?: Array<string>;
};

export type CancelProjectDto = {
    reason: string;
};

export type SubmitBidDto = {
    projectId: string;
    cost: number;
    timelineDays: number;
    proposal?: string;
    documents?: Array<string>;
};

export type ConfirmProjectCompletionDto = {
    rating?: number;
    comment?: string;
};

export type DesignConsultancyProfileDto = {
    companyName: string;
    yearsOfExperience: number;
    specializations: string;
    teamSize: number;
    companyDescription: string;
    serviceAreas: Array<string>;
    companyRegistrationCertificate?: Array<string>;
    taxRegistrationCertificate: Array<string>;
    companyLogo: Array<string>;
};

export type DesignConsultancySignupDto = {
    email: string;
    address: string;
    password: string;
    phone?: string;
    fullName: string;
    loginType?: UserLoginType;
    details: DesignConsultancyProfileDto;
};

export type UpdateDesignConsultancyProfileDto = {
    fullName?: string;
    phone?: string;
    address?: string;
    details?: DesignConsultancyProfileDto;
};

export type PortfolioProjectDto = {
    projectName: string;
    description: string;
    notableClients?: string;
    averageProjectValue?: number;
    projectPhotos?: Array<string>;
};

export type UpdatePortfolioProjectDto = {
    projectName?: string;
    description?: string;
    notableClients?: string;
    averageProjectValue?: number;
    projectPhotos?: Array<string>;
};

export type ContractorProfileDto = {
    companyName: string;
    yearsOfExperience: number;
    specializations: string;
    teamSize: string;
    companyDescription: string;
    serviceAreas: Array<string>;
    companyRegistrationCertificate?: Array<string>;
    taxRegistrationCertificate?: Array<string>;
    personalLicense?: Array<string>;
    companyLogo?: Array<string>;
    insuranceDocument?: Array<string>;
};

export type ContractorSignupDto = {
    email: string;
    address: string;
    password: string;
    phone?: string;
    fullName: string;
    loginType?: UserLoginType;
    details: ContractorProfileDto;
};

export type UpdateContractorProfileDto = {
    fullName?: string;
    phone?: string;
    details?: ContractorProfileDto;
};

export type ClientProfileDto = {
    clientType: ClientType;
    companyName?: string;
    billingAddress?: string;
    contactPerson?: string;
    vatNumber?: string;
    companyRegistrationNo?: string;
    panNumber?: string;
    extraData?: unknown;
    citizenshipCertificates?: Array<string>;
    companyDocuments?: Array<string>;
};

export type ClientSignupDto = {
    email: string;
    password: string;
    address?: string;
    phone?: string;
    fullName: string;
    loginType?: UserLoginType;
    details: ClientProfileDto;
};

export type UpdateClientProfileDto = {
    fullName?: string;
    phone?: string;
    details?: ClientProfileDto;
};

export type ReviewDto = {
    contractorId: string;
    projectId: string;
    rating: number;
    comment?: string;
};

export type RejectBidDto = {
    reason: string;
};

export type ResponseInterfaceUser = {
    data: User | null;
    success: boolean;
    message: string;
    status?: string;
    pagination?: PaginationInterface;
};

export type AgentSignupDto = {
    email: string;
    password: string;
    phone: string;
    fullName: string;
    address?: string;
};

export type ResponseInterfaceUserArray = {
    data: Array<User> | null;
    success: boolean;
    message: string;
    status?: string;
    pagination?: PaginationInterface;
};

/**
 * Make all properties in T optional
 */
export type PartialUpdateAgentProfileDto = {
    fullName?: string;
};

/**
 * Make all properties in T optional
 */
export type PartialBlog = {
    title?: string;
    slug?: string;
    content?: string;
    isPublished?: boolean;
    author?: User;
    authorId?: string;
    featuredImage?: Media;
    featuredImageId?: string;
    category?: string;
    tags?: Array<string>;
    id?: string;
    createdAt?: string;
    updatedAt?: string;
    deletedAt?: string;
};

export type GetUserNotificationsData = {
    body?: never;
    path?: never;
    query?: {
        page?: number;
        limit?: number;
    };
    url: '/api/v1/notifications';
};

export type GetUserNotificationsResponses = {
    /**
     * Ok
     */
    200: ResponseInterfaceDataNotificationArrayCountNumber;
};

export type GetUserNotificationsResponse = GetUserNotificationsResponses[keyof GetUserNotificationsResponses];

export type GetUnreadCountData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/notifications/unread-count';
};

export type GetUnreadCountResponses = {
    /**
     * Ok
     */
    200: ResponseInterfaceCountNumber;
};

export type GetUnreadCountResponse = GetUnreadCountResponses[keyof GetUnreadCountResponses];

export type MarkAsReadData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/notifications/{id}/read';
};

export type MarkAsReadResponses = {
    /**
     * Ok
     */
    200: ResponseInterfaceNotification;
};

export type MarkAsReadResponse = MarkAsReadResponses[keyof MarkAsReadResponses];

export type MarkAllAsReadData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/notifications/read-all';
};

export type MarkAllAsReadResponses = {
    /**
     * All notifications marked as read
     */
    200: ResponseInterfaceNull;
};

export type MarkAllAsReadResponse = MarkAllAsReadResponses[keyof MarkAllAsReadResponses];

export type UploadMediaData = {
    body: {
        file: Blob | File;
        documentType: string;
        entityType: string;
        entityId?: string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/media/upload';
};

export type UploadMediaResponses = {
    /**
     * Created
     */
    201: ResponseInterfaceMediaResponseDto;
};

export type UploadMediaResponse = UploadMediaResponses[keyof UploadMediaResponses];

export type DownloadMediaData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/media/download/{id}';
};

export type DownloadMediaResponses = {
    /**
     * Ok
     */
    200: ResponseInterfaceAny;
};

export type DownloadMediaResponse = DownloadMediaResponses[keyof DownloadMediaResponses];

export type GetAllMediaData = {
    body?: never;
    path?: never;
    query?: {
        entityType?: MediaEntityType;
        entityId?: string;
        page?: number;
        limit?: number;
    };
    url: '/api/v1/media';
};

export type GetAllMediaResponses = {
    /**
     * Ok
     */
    200: ResponseInterfaceMediaResponseDtoArray;
};

export type GetAllMediaResponse = GetAllMediaResponses[keyof GetAllMediaResponses];

export type DeleteMediaData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/media/{id}';
};

export type DeleteMediaResponses = {
    /**
     * Ok
     */
    200: ResponseInterfaceAny;
};

export type DeleteMediaResponse = DeleteMediaResponses[keyof DeleteMediaResponses];

export type GetMediaByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/media/{id}';
};

export type GetMediaByIdResponses = {
    /**
     * Ok
     */
    200: ResponseInterfaceMediaResponseDto;
};

export type GetMediaByIdResponse = GetMediaByIdResponses[keyof GetMediaByIdResponses];

export type UpdateMediaData = {
    body: {
        name?: string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/media/{id}';
};

export type UpdateMediaResponses = {
    /**
     * Ok
     */
    200: ResponseInterfaceMediaResponseDto;
};

export type UpdateMediaResponse = UpdateMediaResponses[keyof UpdateMediaResponses];

export type GetMyLogsData = {
    body?: never;
    path?: never;
    query?: {
        page?: number;
        limit?: number;
    };
    url: '/api/v1/logs/my-logs';
};

export type GetMyLogsResponses = {
    /**
     * Ok
     */
    200: ResponseInterfaceAny;
};

export type GetMyLogsResponse = GetMyLogsResponses[keyof GetMyLogsResponses];

export type GetLogsByUserIdData = {
    body?: never;
    path: {
        userId: string;
    };
    query?: {
        page?: number;
        limit?: number;
    };
    url: '/api/v1/logs/user/{userId}';
};

export type GetLogsByUserIdResponses = {
    /**
     * Ok
     */
    200: ResponseInterfaceAny;
};

export type GetLogsByUserIdResponse = GetLogsByUserIdResponses[keyof GetLogsByUserIdResponses];

export type RootData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type RootResponses = {
    /**
     * Ok
     */
    200: {
        env: string;
        version: unknown;
        uptime: string;
        status: string;
    };
};

export type RootResponse = RootResponses[keyof RootResponses];

export type HealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthResponses = {
    /**
     * Ok
     */
    200: {
        time: string;
        redis: string;
        db: string;
        env: string;
        version: unknown;
        uptime: number;
        status: string;
    };
};

export type HealthResponse = HealthResponses[keyof HealthResponses];

export type GetAllMessagesData = {
    body?: never;
    path?: never;
    query?: {
        limit?: number;
        page?: number;
        status?: string;
    };
    url: '/api/v1/contact-us';
};

export type GetAllMessagesResponses = {
    /**
     * Ok
     */
    200: ResponseInterfaceContactUsArray;
};

export type GetAllMessagesResponse = GetAllMessagesResponses[keyof GetAllMessagesResponses];

export type SubmitContactFormData = {
    body: CreateContactUsDto;
    path?: never;
    query?: never;
    url: '/api/v1/contact-us';
};

export type SubmitContactFormResponses = {
    /**
     * Ok
     */
    200: ResponseInterfaceContactUs;
};

export type SubmitContactFormResponse = SubmitContactFormResponses[keyof SubmitContactFormResponses];

export type DeleteMessageData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/contact-us/{id}';
};

export type DeleteMessageResponses = {
    /**
     * Ok
     */
    200: ResponseInterfaceNull;
};

export type DeleteMessageResponse = DeleteMessageResponses[keyof DeleteMessageResponses];

export type GetMessageByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/contact-us/{id}';
};

export type GetMessageByIdResponses = {
    /**
     * Ok
     */
    200: ResponseInterfaceContactUs;
};

export type GetMessageByIdResponse = GetMessageByIdResponses[keyof GetMessageByIdResponses];

export type UpdateStatusData = {
    body: UpdateContactUsStatusDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/contact-us/{id}/status';
};

export type UpdateStatusResponses = {
    /**
     * Ok
     */
    200: ResponseInterfaceContactUs;
};

export type UpdateStatusResponse = UpdateStatusResponses[keyof UpdateStatusResponses];

export type GetPublishedBlogsData = {
    body?: never;
    path?: never;
    query?: {
        limit?: number;
        page?: number;
        search?: string;
    };
    url: '/api/v1/blogs';
};

export type GetPublishedBlogsResponses = {
    /**
     * Ok
     */
    200: ResponseInterfaceBlogArray;
};

export type GetPublishedBlogsResponse = GetPublishedBlogsResponses[keyof GetPublishedBlogsResponses];

export type GetBlogBySlugData = {
    body?: never;
    path: {
        slug: string;
    };
    query?: never;
    url: '/api/v1/blogs/{slug}';
};

export type GetBlogBySlugResponses = {
    /**
     * Ok
     */
    200: ResponseInterfaceBlog;
};

export type GetBlogBySlugResponse = GetBlogBySlugResponses[keyof GetBlogBySlugResponses];

export type VerifyEmailData = {
    body: VerifyEmailDto;
    path?: never;
    query?: never;
    url: '/api/v1/auth/verify-email';
};

export type VerifyEmailResponses = {
    /**
     * Verified
     */
    200: ResponseInterfaceAny;
};

export type VerifyEmailResponse = VerifyEmailResponses[keyof VerifyEmailResponses];

export type ResendOtpData = {
    body: ResendOtpDto;
    path?: never;
    query?: never;
    url: '/api/v1/auth/resend-otp';
};

export type ResendOtpResponses = {
    /**
     * OTP Sent
     */
    200: ResponseInterfaceNull;
};

export type ResendOtpResponse = ResendOtpResponses[keyof ResendOtpResponses];

export type LoginData = {
    body: UserLoginDto;
    path?: never;
    query?: never;
    url: '/api/v1/auth/login';
};

export type LoginResponses = {
    /**
     * Ok
     */
    200: unknown;
};

export type LogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/logout';
};

export type LogoutResponses = {
    /**
     * Ok
     */
    200: ResponseInterfaceAny;
};

export type LogoutResponse = LogoutResponses[keyof LogoutResponses];

export type RefreshTokenData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/refresh-token';
};

export type RefreshTokenResponses = {
    /**
     * Ok
     */
    200: ResponseInterfaceAny;
};

export type RefreshTokenResponse = RefreshTokenResponses[keyof RefreshTokenResponses];

export type ForgotPasswordData = {
    body: UserForgotPasswordDto;
    path?: never;
    query?: never;
    url: '/api/v1/auth/forgot-password';
};

export type ForgotPasswordResponses = {
    /**
     * Password reset OTP sent to your email
     */
    200: ResponseInterfaceNull;
};

export type ForgotPasswordResponse = ForgotPasswordResponses[keyof ForgotPasswordResponses];

export type ResetPasswordData = {
    body: UserResetPasswordDto;
    path?: never;
    query?: never;
    url: '/api/v1/auth/reset-password';
};

export type ResetPasswordResponses = {
    /**
     * Ok
     */
    200: ResponseInterfaceNull;
};

export type ResetPasswordResponse = ResetPasswordResponses[keyof ResetPasswordResponses];

export type InitiateChangePasswordData = {
    body: ChangePasswordInitiateDto;
    path?: never;
    query?: never;
    url: '/api/v1/auth/change-password/initiate';
};

export type InitiateChangePasswordResponses = {
    /**
     * OTP Sent
     */
    200: ResponseInterfaceNull;
};

export type InitiateChangePasswordResponse = InitiateChangePasswordResponses[keyof InitiateChangePasswordResponses];

export type ConfirmChangePasswordData = {
    body: ChangePasswordConfirmDto;
    path?: never;
    query?: never;
    url: '/api/v1/auth/change-password/confirm';
};

export type ConfirmChangePasswordResponses = {
    /**
     * Password Changed
     */
    200: ResponseInterfaceNull;
};

export type ConfirmChangePasswordResponse = ConfirmChangePasswordResponses[keyof ConfirmChangePasswordResponses];

export type GetMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/me';
};

export type GetMeResponses = {
    /**
     * Ok
     */
    200: ResponseInterfaceAny;
};

export type GetMeResponse = GetMeResponses[keyof GetMeResponses];

export type GetUserDetailsData = {
    body?: never;
    path: {
        id: string;
    };
    query: {
        role: UserRole;
    };
    url: '/api/v1/users/{id}';
};

export type GetUserDetailsResponses = {
    /**
     * Ok
     */
    200: ResponseInterfaceAny;
};

export type GetUserDetailsResponse = GetUserDetailsResponses[keyof GetUserDetailsResponses];

export type GetPendingVerificationsData = {
    body?: never;
    path?: never;
    query?: {
        search?: string;
        page?: number;
        limit?: number;
        status?: UserVerificationStatus;
        role?: UserRole;
    };
    url: '/api/v1/users/verifications/pending';
};

export type GetPendingVerificationsResponses = {
    /**
     * Ok
     */
    200: ResponseInterfaceAny;
};

export type GetPendingVerificationsResponse = GetPendingVerificationsResponses[keyof GetPendingVerificationsResponses];

export type GetUserVerificationsData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/users/{id}/verifications';
};

export type GetUserVerificationsResponses = {
    /**
     * Ok
     */
    200: ResponseInterfaceAnyArray;
};

export type GetUserVerificationsResponse = GetUserVerificationsResponses[keyof GetUserVerificationsResponses];

export type VerifyContractorData = {
    body: VerifyContractorDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/users/contractors/{id}/verify';
};

export type VerifyContractorResponses = {
    /**
     * Verified
     */
    200: ResponseInterfaceAny;
};

export type VerifyContractorResponse = VerifyContractorResponses[keyof VerifyContractorResponses];

export type VerifyClientData = {
    body: VerifyClientDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/users/clients/{id}/verify';
};

export type VerifyClientResponses = {
    /**
     * Verified
     */
    200: unknown;
};

export type VerifyDesignConsultancyData = {
    body: VerifyDesignConsultancyDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/users/consultancy/{id}/verify';
};

export type VerifyDesignConsultancyResponses = {
    /**
     * Verified
     */
    200: ResponseInterfaceNull;
};

export type VerifyDesignConsultancyResponse = VerifyDesignConsultancyResponses[keyof VerifyDesignConsultancyResponses];

export type SubmitReviewData = {
    body: SubmitReviewDto;
    path: {
        projectId: string;
    };
    query?: never;
    url: '/api/v1/reviews/project/{projectId}';
};

export type SubmitReviewResponses = {
    /**
     * Ok
     */
    200: ResponseInterfaceAny;
};

export type SubmitReviewResponse = SubmitReviewResponses[keyof SubmitReviewResponses];

export type GetUserReviewsData = {
    body?: never;
    path: {
        userId: string;
    };
    query?: never;
    url: '/api/v1/reviews/user/{userId}';
};

export type GetUserReviewsResponses = {
    /**
     * Ok
     */
    200: ResponseInterfaceAny;
};

export type GetUserReviewsResponse = GetUserReviewsResponses[keyof GetUserReviewsResponses];

export type GetProjectsData = {
    body?: never;
    path?: never;
    query?: {
        search?: string;
        status?: ProjectStatus;
        category?: ProjectCategory;
        page?: number;
        limit?: number;
        maxBudget?: number;
        minBudget?: number;
        budgetType?: ProjectBudgetType;
    };
    url: '/api/v1/projects';
};

export type GetProjectsResponses = {
    /**
     * Ok
     */
    200: ResponseInterfaceAny;
};

export type GetProjectsResponse = GetProjectsResponses[keyof GetProjectsResponses];

export type CreateProjectData = {
    body: CreateProjectDto;
    path?: never;
    query?: never;
    url: '/api/v1/projects';
};

export type CreateProjectResponses = {
    /**
     * Created
     */
    201: ResponseInterfaceAny;
};

export type CreateProjectResponse = CreateProjectResponses[keyof CreateProjectResponses];

export type GetMyProjectsData = {
    body?: never;
    path?: never;
    query?: {
        search?: string;
        status?: ProjectStatus;
    };
    url: '/api/v1/projects/my-projects';
};

export type GetMyProjectsResponses = {
    /**
     * Ok
     */
    200: ResponseInterfaceAny;
};

export type GetMyProjectsResponse = GetMyProjectsResponses[keyof GetMyProjectsResponses];

export type DeleteProjectData = {
    body?: never;
    path: {
        projectId: string;
    };
    query?: never;
    url: '/api/v1/projects/{projectId}';
};

export type DeleteProjectResponses = {
    /**
     * Ok
     */
    200: ResponseInterfaceNull;
};

export type DeleteProjectResponse = DeleteProjectResponses[keyof DeleteProjectResponses];

export type GetProjectDetailsData = {
    body?: never;
    path: {
        projectId: string;
    };
    query?: never;
    url: '/api/v1/projects/{projectId}';
};

export type GetProjectDetailsResponses = {
    /**
     * Ok
     */
    200: ResponseInterfaceAny;
};

export type GetProjectDetailsResponse = GetProjectDetailsResponses[keyof GetProjectDetailsResponses];

export type UpdateProjectData = {
    body: UpdateProjectDto;
    path: {
        projectId: string;
    };
    query?: never;
    url: '/api/v1/projects/{projectId}';
};

export type UpdateProjectResponses = {
    /**
     * Ok
     */
    200: ResponseInterfaceAny;
};

export type UpdateProjectResponse = UpdateProjectResponses[keyof UpdateProjectResponses];

export type GetProjectBySlugData = {
    body?: never;
    path: {
        slug: string;
    };
    query?: {
        target?: ProjectTarget;
    };
    url: '/api/v1/projects/slug/{slug}';
};

export type GetProjectBySlugResponses = {
    /**
     * Ok
     */
    200: ResponseInterfaceAny;
};

export type GetProjectBySlugResponse = GetProjectBySlugResponses[keyof GetProjectBySlugResponses];

export type UpdateProjectByAdminData = {
    body: UpdateProjectDtoByAdmin;
    path: {
        projectId: string;
    };
    query?: never;
    url: '/api/v1/projects/{projectId}/by-admin';
};

export type UpdateProjectByAdminResponses = {
    /**
     * Ok
     */
    200: ResponseInterfaceAny;
};

export type UpdateProjectByAdminResponse = UpdateProjectByAdminResponses[keyof UpdateProjectByAdminResponses];

export type CancelProjectData = {
    body: CancelProjectDto;
    path: {
        projectId: string;
    };
    query?: never;
    url: '/api/v1/projects/{projectId}/cancel';
};

export type CancelProjectResponses = {
    /**
     * Ok
     */
    200: ResponseInterfaceAny;
};

export type CancelProjectResponse = CancelProjectResponses[keyof CancelProjectResponses];

export type GetProjectBidsData = {
    body?: never;
    path: {
        projectId: string;
    };
    query?: {
        page?: number;
        limit?: number;
        search?: string;
        status?: BidStatus;
    };
    url: '/api/v1/projects/{projectId}/bids';
};

export type GetProjectBidsResponses = {
    /**
     * Ok
     */
    200: ResponseInterfaceAny;
};

export type GetProjectBidsResponse = GetProjectBidsResponses[keyof GetProjectBidsResponses];

export type SubmitBidData = {
    body: SubmitBidDto;
    path: {
        projectId: string;
    };
    query?: never;
    url: '/api/v1/projects/{projectId}/bids';
};

export type SubmitBidResponses = {
    /**
     * Ok
     */
    200: ResponseInterfaceAny;
};

export type SubmitBidResponse = SubmitBidResponses[keyof SubmitBidResponses];

export type SelectBidData = {
    body?: never;
    path: {
        projectId: string;
        bidId: string;
    };
    query?: never;
    url: '/api/v1/projects/{projectId}/bids/{bidId}/select';
};

export type SelectBidResponses = {
    /**
     * Ok
     */
    200: ResponseInterfaceAny;
};

export type SelectBidResponse = SelectBidResponses[keyof SelectBidResponses];

export type GetParticipationReportData = {
    body?: never;
    path: {
        projectId: string;
    };
    query?: never;
    url: '/api/v1/projects/{projectId}/participation-report';
};

export type GetParticipationReportResponses = {
    /**
     * No content
     */
    204: void;
};

export type GetParticipationReportResponse = GetParticipationReportResponses[keyof GetParticipationReportResponses];

export type MarkAsCompletedData = {
    body?: never;
    path: {
        projectId: string;
    };
    query?: never;
    url: '/api/v1/projects/{projectId}/mark-completed';
};

export type MarkAsCompletedResponses = {
    /**
     * Ok
     */
    200: ResponseInterfaceAny;
};

export type MarkAsCompletedResponse = MarkAsCompletedResponses[keyof MarkAsCompletedResponses];

export type ConfirmCompletionData = {
    body: ConfirmProjectCompletionDto;
    path: {
        projectId: string;
    };
    query?: never;
    url: '/api/v1/projects/{projectId}/confirm-completion';
};

export type ConfirmCompletionResponses = {
    /**
     * Ok
     */
    200: ResponseInterfaceAny;
};

export type ConfirmCompletionResponse = ConfirmCompletionResponses[keyof ConfirmCompletionResponses];

export type SignupData = {
    body: DesignConsultancySignupDto;
    path?: never;
    query?: never;
    url: '/api/v1/design-consultancies/signup';
};

export type SignupResponses = {
    /**
     * Created
     */
    201: ResponseInterfaceAny;
};

export type SignupResponse = SignupResponses[keyof SignupResponses];

export type GetProfileData = {
    body?: never;
    path: {
        userId: string;
    };
    query?: never;
    url: '/api/v1/design-consultancies/profile/{userId}';
};

export type GetProfileResponses = {
    /**
     * Ok
     */
    200: ResponseInterfaceAny;
};

export type GetProfileResponse = GetProfileResponses[keyof GetProfileResponses];

export type UpdateProfileData = {
    body: UpdateDesignConsultancyProfileDto;
    path: {
        userId: string;
    };
    query?: never;
    url: '/api/v1/design-consultancies/profile/{userId}';
};

export type UpdateProfileResponses = {
    /**
     * Ok
     */
    200: ResponseInterfaceAny;
};

export type UpdateProfileResponse = UpdateProfileResponses[keyof UpdateProfileResponses];

export type GetDashboardStatsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/design-consultancies/dashboard/stats';
};

export type GetDashboardStatsResponses = {
    /**
     * Ok
     */
    200: ResponseInterfaceAny;
};

export type GetDashboardStatsResponse = GetDashboardStatsResponses[keyof GetDashboardStatsResponses];

export type GetPortfolioProjectsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/design-consultancies/portfolio';
};

export type GetPortfolioProjectsResponses = {
    /**
     * Ok
     */
    200: ResponseInterfaceAny;
};

export type GetPortfolioProjectsResponse = GetPortfolioProjectsResponses[keyof GetPortfolioProjectsResponses];

export type AddPortfolioProjectData = {
    body: PortfolioProjectDto;
    path?: never;
    query?: never;
    url: '/api/v1/design-consultancies/portfolio';
};

export type AddPortfolioProjectResponses = {
    /**
     * Created
     */
    201: ResponseInterfaceAny;
};

export type AddPortfolioProjectResponse = AddPortfolioProjectResponses[keyof AddPortfolioProjectResponses];

export type DeletePortfolioProjectData = {
    body?: never;
    path: {
        projectId: string;
    };
    query?: never;
    url: '/api/v1/design-consultancies/portfolio/{projectId}';
};

export type DeletePortfolioProjectResponses = {
    /**
     * Ok
     */
    200: ResponseInterfaceAny;
};

export type DeletePortfolioProjectResponse = DeletePortfolioProjectResponses[keyof DeletePortfolioProjectResponses];

export type UpdatePortfolioProjectData = {
    body: UpdatePortfolioProjectDto;
    path: {
        projectId: string;
    };
    query?: never;
    url: '/api/v1/design-consultancies/portfolio/{projectId}';
};

export type UpdatePortfolioProjectResponses = {
    /**
     * Ok
     */
    200: ResponseInterfaceAny;
};

export type UpdatePortfolioProjectResponse = UpdatePortfolioProjectResponses[keyof UpdatePortfolioProjectResponses];

export type RemovePhotoData = {
    body?: never;
    path: {
        projectId: string;
        photoId: string;
    };
    query?: never;
    url: '/api/v1/design-consultancies/portfolio/{projectId}/photo/{photoId}';
};

export type RemovePhotoResponses = {
    /**
     * Ok
     */
    200: ResponseInterfaceAny;
};

export type RemovePhotoResponse = RemovePhotoResponses[keyof RemovePhotoResponses];

export type Signup2Data = {
    body: ContractorSignupDto;
    path?: never;
    query?: never;
    url: '/api/v1/contractors/signup';
};

export type Signup2Responses = {
    /**
     * Created
     */
    201: ResponseInterfaceAny;
};

export type Signup2Response = Signup2Responses[keyof Signup2Responses];

export type GetProfile2Data = {
    body?: never;
    path: {
        userId: string;
    };
    query?: never;
    url: '/api/v1/contractors/profile/{userId}';
};

export type GetProfile2Responses = {
    /**
     * Ok
     */
    200: ResponseInterfaceAny;
};

export type GetProfile2Response = GetProfile2Responses[keyof GetProfile2Responses];

export type UpdateProfile2Data = {
    body: UpdateContractorProfileDto;
    path: {
        userId: string;
    };
    query?: never;
    url: '/api/v1/contractors/profile/{userId}';
};

export type UpdateProfile2Responses = {
    /**
     * Ok
     */
    200: ResponseInterfaceAny;
};

export type UpdateProfile2Response = UpdateProfile2Responses[keyof UpdateProfile2Responses];

export type AddPortfolioProject2Data = {
    body: PortfolioProjectDto;
    path?: never;
    query?: never;
    url: '/api/v1/contractors/portfolio';
};

export type AddPortfolioProject2Responses = {
    /**
     * Created
     */
    201: ResponseInterfaceAny;
};

export type AddPortfolioProject2Response = AddPortfolioProject2Responses[keyof AddPortfolioProject2Responses];

export type DeletePortfolioProject2Data = {
    body?: never;
    path: {
        projectId: string;
    };
    query?: never;
    url: '/api/v1/contractors/portfolio/{projectId}';
};

export type DeletePortfolioProject2Responses = {
    /**
     * Ok
     */
    200: ResponseInterfaceAny;
};

export type DeletePortfolioProject2Response = DeletePortfolioProject2Responses[keyof DeletePortfolioProject2Responses];

export type UpdatePortfolioProject2Data = {
    body: UpdatePortfolioProjectDto;
    path: {
        projectId: string;
    };
    query?: never;
    url: '/api/v1/contractors/portfolio/{projectId}';
};

export type UpdatePortfolioProject2Responses = {
    /**
     * Ok
     */
    200: ResponseInterfaceAny;
};

export type UpdatePortfolioProject2Response = UpdatePortfolioProject2Responses[keyof UpdatePortfolioProject2Responses];

export type RemovePhoto2Data = {
    body?: never;
    path: {
        projectId: string;
        photoId: string;
    };
    query?: never;
    url: '/api/v1/contractors/portfolio/{projectId}/photo/{photoId}';
};

export type RemovePhoto2Responses = {
    /**
     * Ok
     */
    200: ResponseInterfaceAny;
};

export type RemovePhoto2Response = RemovePhoto2Responses[keyof RemovePhoto2Responses];

export type ToggleAvailabilityData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/contractors/availability';
};

export type ToggleAvailabilityResponses = {
    /**
     * Ok
     */
    200: ResponseInterfaceAny;
};

export type ToggleAvailabilityResponse = ToggleAvailabilityResponses[keyof ToggleAvailabilityResponses];

export type GetContractorDashboardStatsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/contractors/dashboard/stats';
};

export type GetContractorDashboardStatsResponses = {
    /**
     * Ok
     */
    200: ResponseInterfaceAny;
};

export type GetContractorDashboardStatsResponse = GetContractorDashboardStatsResponses[keyof GetContractorDashboardStatsResponses];

export type Signup3Data = {
    body: ClientSignupDto;
    path?: never;
    query?: never;
    url: '/api/v1/clients/signup';
};

export type Signup3Responses = {
    /**
     * Created
     */
    201: ResponseInterfaceAny;
};

export type Signup3Response = Signup3Responses[keyof Signup3Responses];

export type GetProfile3Data = {
    body?: never;
    path: {
        userId: string;
    };
    query?: never;
    url: '/api/v1/clients/profile/{userId}';
};

export type GetProfile3Responses = {
    /**
     * Ok
     */
    200: ResponseInterfaceAny;
};

export type GetProfile3Response = GetProfile3Responses[keyof GetProfile3Responses];

export type UpdateProfile3Data = {
    body: UpdateClientProfileDto;
    path: {
        userId: string;
    };
    query?: never;
    url: '/api/v1/clients/profile/{userId}';
};

export type UpdateProfile3Responses = {
    /**
     * Ok
     */
    200: ResponseInterfaceAny;
};

export type UpdateProfile3Response = UpdateProfile3Responses[keyof UpdateProfile3Responses];

export type GetDashboardStats2Data = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/clients/dashboard/stats';
};

export type GetDashboardStats2Responses = {
    /**
     * Ok
     */
    200: ResponseInterfaceAny;
};

export type GetDashboardStats2Response = GetDashboardStats2Responses[keyof GetDashboardStats2Responses];

export type AddReviewData = {
    body: ReviewDto;
    path?: never;
    query?: never;
    url: '/api/v1/clients/review';
};

export type AddReviewResponses = {
    /**
     * Created
     */
    201: ResponseInterfaceAny;
};

export type AddReviewResponse = AddReviewResponses[keyof AddReviewResponses];

export type GetMyBidsData = {
    body?: never;
    path?: never;
    query?: {
        page?: number;
        limit?: number;
    };
    url: '/api/v1/bids/my-bids';
};

export type GetMyBidsResponses = {
    /**
     * Ok
     */
    200: ResponseInterfaceAny;
};

export type GetMyBidsResponse = GetMyBidsResponses[keyof GetMyBidsResponses];

export type GetBidsByContractorData = {
    body?: never;
    path: {
        contractorId: string;
    };
    query?: {
        page?: number;
        limit?: number;
    };
    url: '/api/v1/bids/{contractorId}';
};

export type GetBidsByContractorResponses = {
    /**
     * Ok
     */
    200: ResponseInterfaceAny;
};

export type GetBidsByContractorResponse = GetBidsByContractorResponses[keyof GetBidsByContractorResponses];

export type RejectBidData = {
    body: RejectBidDto;
    path: {
        bidId: string;
    };
    query?: never;
    url: '/api/v1/bids/reject/{bidId}';
};

export type RejectBidResponses = {
    /**
     * Ok
     */
    200: ResponseInterfaceAny;
};

export type RejectBidResponse = RejectBidResponses[keyof RejectBidResponses];

export type CreateAgentData = {
    body: AgentSignupDto;
    path?: never;
    query?: never;
    url: '/api/v1/agents/signup';
};

export type CreateAgentResponses = {
    /**
     * Created
     */
    201: ResponseInterfaceUser;
};

export type CreateAgentResponse = CreateAgentResponses[keyof CreateAgentResponses];

export type GetAgentsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/agents';
};

export type GetAgentsResponses = {
    /**
     * Ok
     */
    200: ResponseInterfaceUserArray;
};

export type GetAgentsResponse = GetAgentsResponses[keyof GetAgentsResponses];

export type DeleteAgentData = {
    body?: never;
    path: {
        agentId: string;
    };
    query?: never;
    url: '/api/v1/agents/{agentId}';
};

export type DeleteAgentResponses = {
    /**
     * Ok
     */
    200: ResponseInterfaceNull;
};

export type DeleteAgentResponse = DeleteAgentResponses[keyof DeleteAgentResponses];

export type GetAgentData = {
    body?: never;
    path: {
        agentId: string;
    };
    query?: never;
    url: '/api/v1/agents/{agentId}';
};

export type GetAgentResponses = {
    /**
     * Ok
     */
    200: ResponseInterfaceUser;
};

export type GetAgentResponse = GetAgentResponses[keyof GetAgentResponses];

export type UpdateAgentData = {
    body: PartialUpdateAgentProfileDto;
    path: {
        agentId: string;
    };
    query?: never;
    url: '/api/v1/agents/{agentId}';
};

export type UpdateAgentResponses = {
    /**
     * Ok
     */
    200: ResponseInterfaceUser;
};

export type UpdateAgentResponse = UpdateAgentResponses[keyof UpdateAgentResponses];

export type GetProfile4Data = {
    body?: never;
    path: {
        agentId: string;
    };
    query?: never;
    url: '/api/v1/agents/{agentId}/profile';
};

export type GetProfile4Responses = {
    /**
     * Ok
     */
    200: ResponseInterfaceAny;
};

export type GetProfile4Response = GetProfile4Responses[keyof GetProfile4Responses];

export type GetDashboardStats3Data = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/agents/dashboard/stats';
};

export type GetDashboardStats3Responses = {
    /**
     * Ok
     */
    200: ResponseInterfaceAny;
};

export type GetDashboardStats3Response = GetDashboardStats3Responses[keyof GetDashboardStats3Responses];

export type GetBlogsData = {
    body?: never;
    path?: never;
    query?: {
        limit?: number;
        page?: number;
        search?: string;
    };
    url: '/api/v1/admin/blogs';
};

export type GetBlogsResponses = {
    /**
     * Ok
     */
    200: ResponseInterfaceBlogArray;
};

export type GetBlogsResponse = GetBlogsResponses[keyof GetBlogsResponses];

export type CreateBlogData = {
    body: PartialBlog;
    path?: never;
    query?: never;
    url: '/api/v1/admin/blogs';
};

export type CreateBlogResponses = {
    /**
     * Ok
     */
    200: ResponseInterfaceBlog;
};

export type CreateBlogResponse = CreateBlogResponses[keyof CreateBlogResponses];

export type DeleteBlogData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/admin/blogs/{id}';
};

export type DeleteBlogResponses = {
    /**
     * Ok
     */
    200: ResponseInterfaceNull;
};

export type DeleteBlogResponse = DeleteBlogResponses[keyof DeleteBlogResponses];

export type UpdateBlogData = {
    body: PartialBlog;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/admin/blogs/{id}';
};

export type UpdateBlogResponses = {
    /**
     * Ok
     */
    200: ResponseInterfaceBlog;
};

export type UpdateBlogResponse = UpdateBlogResponses[keyof UpdateBlogResponses];

export type GetDashboardData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/admin/dashboard';
};

export type GetDashboardResponses = {
    /**
     * Ok
     */
    200: ResponseInterfaceAny;
};

export type GetDashboardResponse = GetDashboardResponses[keyof GetDashboardResponses];

export type GetAnalyticsOverviewData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/admin/analytics-overview';
};

export type GetAnalyticsOverviewResponses = {
    /**
     * Ok
     */
    200: ResponseInterfaceAny;
};

export type GetAnalyticsOverviewResponse = GetAnalyticsOverviewResponses[keyof GetAnalyticsOverviewResponses];

export type GetAllUsersData = {
    body?: never;
    path?: never;
    query?: {
        search?: string;
        role?: string;
    };
    url: '/api/v1/admin/users';
};

export type GetAllUsersResponses = {
    /**
     * Ok
     */
    200: ResponseInterfaceAnyArray;
};

export type GetAllUsersResponse = GetAllUsersResponses[keyof GetAllUsersResponses];
